### ISSUE TITLE
Barbican Installation Checklist

### ISSUE THREAD

**Issue by obviousjim** [CLOUDS-Interactive-Documentary/CLOUDS#6]
- [x] loader splash on start up screen
- [x] desktop backgrounds
- [x] auto shut down start up 
- [x] ProcessAlive relauncher
- [x] positioning cluster map window for secondary display
- [x] edit registry to show no UI crash dialog
